#!/usr/bin/env python3

import subprocess
import sys

switches = {
	"sw1":	"192.168.1.11",
	"sw2":	"192.168.1.12",
	"r1":	"192.168.1.1",
	"r2":	"192.168.1.2",
}

if len(sys.argv) <2:
	print("Usage: python3 labssh.py sw1")
	print("Available:", list(switches.keys()))
	sys.exit()

target = sys.argv[1].lower()

if target not in switches:
	print(f"Unkown device:	{target}")
	print("Available:", list(switches.keys()))
	sys.exit()

ip = switches[target]

print("About to ask for username...")
username = input("Enter username: ")

cmd = [
	"ssh",
	"-oKexAlgorithms=+diffie-hellman-group1-sha1",
	"-oHostKeyAlgorithms=+ssh-rsa",
	"-c", "aes128-cbc",
	f"{username}@{ip}"
]

subprocess.run(cmd)	
