#!/usr/bin/env python3

import subprocess
import sys

switches = {
	"sw1":	"10.0.0.11",	# Replace with your SW1 IP			
	"sw2":	"10.0.0.12",	# Replace with your SW2 IP
	"sw3":	"10.0.0.13",	# Replace with your SW3 IP
	"sw4":	"10.0.0.14",	# Replace with your SW4 IP
}

if len(sys.argv) <2:
	print("Usage: python3 labssh.py sw1")
	print("Available:", list(switches.keys()))
	sys.exit()

target = sys.argv[1].lower()

if target not in switches:
	print(f"Unknown device:	{target}")
	print("Available:", list(switches.keys()))
	sys.exit(1)

ip = switches[target]

username = input("Enter username: ")

cmd = [
	"ssh",
	"-oKexAlgorithms=+diffie-hellman-group1-sha1",
	"-oHostKeyAlgorithms=+ssh-rsa",
	"-c", "aes128-cbc",
	f"{username}@{ip}"
]

subprocess.run(cmd)	
