#!/usr/bin/env python3

import subprocess
import sys

switches = {
	"sw1":	"10.0.0.11",	# Replace with your SW1 IP			
	"sw2":	"10.0.0.12",	# Replace with your SW2 IP
	"r1":	"10.0.0.1",		# Replace with your R1 IP
	"r2":	"10.0.0.2",		# Replace with your R2 IP
}

if len(sys.argv) <2:
	print("Usage: python3 labssh.py sw1")
	print("Available:", list(switches.keys()))
	sys.exit()

target = sys.argv[1].lower()

if target not in switches:
	print(f"Unkown device:	{target}")
	print("Available:", list(switches.keys()))
	sys.exit()

ip = switches[target]

print("About to ask for username...")
username = input("Enter username: ")

cmd = [
	"ssh",
	"-oKexAlgorithms=+diffie-hellman-group1-sha1",
	"-oHostKeyAlgorithms=+ssh-rsa",
	"-c", "aes128-cbc",
	f"{username}@{ip}"
]

subprocess.run(cmd)	
